### ISSUE TITLE
v1.x : Cannot read property 'first' of undefined

### ISSUE THREAD

**Issue by Hoya** [joseluisq/prelodr#12]
`if (that) ` 

should be 

`if (that.queu)`

on line 184 of lib/prelodr.js

**Comment by joseluisq** [comment]
Hi, can you provide me more details about this error?
You could consider submit a PR.

**Comment by Hoya** [comment]
Actually not sure exactly what's causing it. It might be a conflict with other JS libs I'm using but I've noticed that ` _queueWalk` would throw that error on `const one = that.queu.first();`. For some reason it looks like `that.queu` is holding a window object and first() can't be called for obvious reasons. I was able to suppress the error by double checking if `that` was holding a `queu`, thus `if (that.queu)`.

**Comment by joseluisq** [comment]
Fixed b10708a
