### ISSUE TITLE
HTML content support

### ISSUE THREAD

**Issue by mozgbrasil** [joseluisq/prelodr#23]
Hello

Good morning my friend

I found your library very cool and I'm testing

I would like to know if how do I insert HTML into PreLoader

I've tried using it this way

Pre.in ( '<a href="xxx"> Processing </a> ...');

But it is displayed as text

**Comment by joseluisq** [comment]
Hi !
Thanks for you feedback!
Yes, `v1` uses `createTextNode()` function to embed text in DOM. 
But now I'm working in `v2` So I'll take this issue as **new feature** and it will be implemented in some hours 😄 
Or if you prefer, you might send me a PR. 👍

**Comment by joseluisq** [comment]
@mozgbrasil done! 
Please check out [v2.0.0](https://github.com/joseluisq/prelodr/releases/tag/2.0.0)

**Comment by mozgbrasil** [comment]
Thank you my friend
